name: allow_lists

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget parallel uchardet curl

      - name: Run Domain List Script
        run: |
          set -euo pipefail
          chmod +x ./domain/allowlist.sh
          ./domain/allowlist.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update allowlist at $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')（北京时间）"
            git push origin HEAD:master
          fi

      - name: Delete Workflow Runs 
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
